# -*- coding: utf-8 -*-
"""first.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nnkVY01Fk0QgspypaIWzlTb7lQKzqUCL
"""

import time
print("Sleeping")
time.sleep(30) # sleep for a while; interrupt me!
print("Done Sleeping")